### ISSUE TITLE
Undefined method `clone_config' 

### ISSUE THREAD

**Issue by rikkipitt** [dalpo/rails_admin_clone#4]
```
NoMethodError at /post/1/clone
undefined method `clone_config' for #<RailsAdmin::Config::Sections::Base:0x007f94dc75a940>
```

Presumably this is due to the latest rails_admin release?

Thought I'd let you know! Can you recreate this error your end? I'm using rails_admin v0.6.6

Rikki

**Comment by weexpectedTHIS** [comment]
I'm pretty sure this has to do with you not putting:

gem 'rails_admin_clone'

in the Gemfile before

gem 'rails_admin'

**Comment by Quent1Pr** [comment]
A fix is available here (not yet merged) https://github.com/dalpo/rails_admin_clone/pull/6
