### ISSUE TITLE
custom_method and associations

### ISSUE THREAD

**Issue by fmh** [dalpo/rails_admin_clone#5]
in my custom_method i want just change title, it works fine, but i loose my object association, do i need Amoeba Gem ? , th clone base method support associations, why not custom_action
I try to set relation objects, it works in view but not when commit data.
```
 def clone_offre
    self.dup.tap do |offer|
      #offer.offer_items = self.offer_items
      offer.title  = "Copy - #{self.title}"
    end
  end
````

**Comment by dalpo** [comment]
Hi @fmh!
Cloning objects, could be very painful.. That's why I suggest to use the Amoeba gem.

You must dup every object. Did you try to dup offer_items too?

```ruby
def clone_offre
  self.dup.tap do |offer|
    offer.offer_items = self.offer_items.map(&:dup)
    offer.title  = "Copy - #{self.title}"
  end
end
```

**Comment by fmh** [comment]
it works , thx 😄
